name = "labsch-api"
main = "src/index.ts"
compatibility_date = "2026-08-30"
account_id = "6915773741f9ea9f8c7a4146bf0ec087"

[triggers]
crons = ["*/5 * * * *"]

[vars]
APP_VERSION = "0.3.0-workers"

[[d1_databases]]
binding = "DB"
database_name = "labsch-db"
database_id = "1e25dc09-462e-4abf-a6ba-a0902707df77"