name = "labsch-api"
main = "src/index.ts"
compatibility_date = "2026-08-30"
account_id = "6915773741f9ea9f8c7a4146bf0ec087"

[triggers]
crons = ["*/5 * * * *"]

[vars]
APP_VERSION = "0.3.5-workers"

[[d1_databases]]
binding = "DB"
database_name = "labsch-db"
database_id = "1e25dc09-462e-4abf-a6ba-a0902707df77"

# Token management KV (created 2026-09-05 via wrangler kv namespace create TOKEN_META)
[[kv_namespaces]]
binding = "TOKEN_META"
id = "80b20c08742e43eb86f05d80d885a3fb"
preview_id = "cc67549c5f2f4632bd9d969cb1c14769"